# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [3]:
# A tool to calculate TF-IDF
tfidf = TfidfVectorizer()
# Train on the docs, convert result to sparse vector
result = tfidf.fit_transform(data) # returns sparce matrix

In [4]:
# Convert the sparse vector into pandas DataFrame
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [7]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [8]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [9]:
pip install gensim

Requirement already satisfied: gensim in c:\users\ruqay\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\ruqay\anaconda3\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\users\ruqay\anaconda3\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\ruqay\anaconda3\lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in c:\users\ruqay\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [11]:
df = pd.read_csv('True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [12]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [ ]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

min_count determines the minimum number of times a word must appear in your corpus to be included in the vocabulary.
vector_size determines the number of dimensions in each word's embedding.
window determines how many words around the target word are considered as its context.
tells Word2Vec which architecture to use (1: skip gram).

In [14]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.44617498

In [15]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programme', 0.8393309116363525), ('programs', 0.7957956790924072), ('arsenal', 0.7160463929176331), ('restraints', 0.705796480178833), ('modernization', 0.7033628225326538), ('programmes', 0.7028630375862122), ('abolishing', 0.6981495022773743), ('bond-buying', 0.6940045952796936), ('EB-5', 0.6851210594177246), ('voucher', 0.6778413653373718)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [16]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
d1 = 'This is the first document.'
d2 = 'This document is the second document.'
d3 = 'And this is the third one.'
d4 = 'Is this the first document?'

docs = [d1,d2,d3,d4]

In [18]:
tfidf = TfidfVectorizer()
vector_m = tfidf.fit_transform(docs)

In [19]:
cosine_similarity_matrix = cosine_similarity(vector_m)
df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=docs, columns=docs)

df_cosine

,This is the first document.,This document is the second document.,And this is the third one.,Is this the first document?
This is the first document.,1.000000,0.646926,0.307772,1.000000
This document is the second document.,0.646926,1.000000,0.225240,0.646926
And this is the third one.,0.307772,0.225240,1.000000,0.307772
Is this the first document?,1.000000,0.646926,0.307772,1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [20]:
s1 = 'data science is one of the most important fields of science'
s2 = 'this is one of the best data science courses'
s3 = 'data scientists analyze data'

data = [s1,s2,s3]

In [21]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) 
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [22]:
df = pd.read_csv('simpsons_script_lines.csv')
df.head()

        raw_character_text                                       spoken_words
0              Miss Hoover  No, actually, it was a little of both. Sometim...
1             Lisa Simpson                             Where's Mr. Bergstrom?
2              Miss Hoover  I don't know. Although I'd sure like to talk t...
3             Lisa Simpson                         That life is worth living.
4  Edna Krabappel-Flanders  The polls will be open from now until the end ...

In [23]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

In [24]:
df['spoken_words'] = df['spoken_words'].fillna('')

In [25]:
df['spoken_words'] = df['spoken_words'].apply(clean_text)
df.head()

        raw_character_text                                       spoken_words
0              Miss Hoover  no actually it was a little of both sometimes ...
1             Lisa Simpson                              where's mr bergstrom?
2              Miss Hoover  i don't know although i'd sure like to talk to...
3             Lisa Simpson                          that life is worth living
4  Edna Krabappel-Flanders  the polls will be open from now until the end ...

In [27]:
tokens = []

for i in df['spoken_words']:
    token = word_tokenize(i)
    tokens.append(token)

In [ ]:
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1, workers=1)

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [29]:
# Words similar to "homer"
print('words similar to homer: ',Skip_gram_model.wv.most_similar("homer"))

words similar to homer:  [('abe', 0.8852932453155518), ('marge', 0.85328209400177), ('bart', 0.8387607932090759), ('grampa', 0.8353449106216431), ('eliza', 0.833375096321106), ('allison', 0.8249243497848511), ('apu', 0.822708785533905), ('kirk', 0.8220445513725281), ('sweetheart', 0.8214932680130005), ('ned', 0.8186942934989929)]

In [30]:
# Words similar to "marge"
print('words similar to marge: ',Skip_gram_model.wv.most_similar("marge"))

words similar to marge:  [('homer', 0.85328209400177), ('abe', 0.8425372242927551), ('lisa', 0.8368734121322632), ('apu', 0.8336910009384155), ('sweetheart', 0.820337176322937), ('becky', 0.8121616840362549), ('sweetie', 0.8096954226493835), ('neddy', 0.8088529706001282), ('allison', 0.8086265325546265), ('greta', 0.7998462319374084)]

In [31]:
# Words similar to "marge"
print('words similar to bart: ',Skip_gram_model.wv.most_similar("bart"))

words similar to bart:  [('lisa', 0.8653364181518555), ('milhouse', 0.8638086318969727), ('homer', 0.8387607932090759), ('eliza', 0.8283503651618958), ('jessica', 0.8276199102401733), ('sweetheart', 0.8249771595001221), ('grampa', 0.8206033110618591), ('nelson', 0.8191031813621521), ('luann', 0.8185974955558777), ('kirk', 0.8157127499580383)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [32]:
# 1
print(Skip_gram_model.wv.doesnt_match(['jimbo', 'milhouse', 'kearney']))

milhouse

In [33]:
# 2
print(Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milhouse']))

nelson

In [34]:
# 3
print(Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

homer